### PR TITLE
For CV

### LINKED ISSUE #357: zabbix_api import in zabbix_conf.py clashes with Ansible zabbix modules
The way the zabbix_api python module is imported clashes with the Ansible zabbix modules. To ensure compatibility, it should be ```from zabbix_api import ZabbixAPIException, ZabbixAPI```. The path in the trix-zabbix-checks RPM should be fixed as well.

### PR DESCRIPTION
**Pull request by tiemenruiten**
- support for auto-registration of hosts in Zabbix. Fixes #357
- fix deprecation warnings from the yum module in Ansible 2.7
- several spelling errors/typo's

### CODE REVIEW

**Comment by hi-a** [comment]
Jenkins test this please

**Comment by tiemenruiten** [comment]
looks like it fails because the latest trix-zabbix-checks with the new templates isn't used?

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Hacked tests a bit to install latest ansible (2.7) form epel, instead of using one from base repo (2.4)
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by tiemenruiten** [comment]
sorry about this, force-pushed the fix to keep things tidy

**Comment by tiemenruiten** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Looks good for me

**Comment by hi-a** [comment]
LGTM

**Pull request merged**
