### PR TITLE
Zabbix on nginx

### PR DESCRIPTION
**Pull request by hi-a**
Use nginx for all web interfaces in trinityX

### CODE REVIEW

**Comment by hi-a** [comment]
jenkins test this please

**Comment by hi-a** [comment]
jenkins test this please

**Comment by kostty** [comment]
looks good

**Comment by hi-a** [comment]
jenkins test this please

**Comment by hi-a** [comment]
Jenkins test this once more please

**Comment by hi-a** [comment]
jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Pull request merged**
