### PR TITLE
Env module fixes

### PR DESCRIPTION
**Pull request by kostty**
Cleaned up the PR a little:
- fix up the previous remarks
- move the userspace repo to the role deps
- move module files path to the role defaults
- removed module files dir creation as it's handled by RPM

### CODE REVIEW

**Comment by kostty** [comment]
Jenkins test this please

**Comment by kostty** [comment]
Jenkins test this please

**Comment by kostty** [comment]
Jenkins test this please

**Comment by kostty** [comment]
Jenkins test this please again

**Comment by dchirikov** [comment]
Looks good

**Pull request merged**
