### PR TITLE
Env pkglist

### PR DESCRIPTION
**Pull request by kostty**
A follow-up PR to #342

### CODE REVIEW

**Comment by kostty** [comment]
jenkins test this please

**Comment by kostty** [comment]
jenkins test this please

**Comment by kostty** [comment]
jenkins test this please

**Comment by kostty** [comment]
jenkins test this please once again

**Comment by kostty** [comment]
jenkins test this please once more

**Comment by kostty** [comment]
jenkins test this please

**Comment by hi-a** [comment]
LGTM

**Pull request merged**
