### PR TITLE
Heartbeat config

### PR DESCRIPTION
**Pull request by hi-a**

### CODE REVIEW

**Comment by kostty** [comment]
Jenkins test this please

**Comment by hi-a** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by dchirikov** [comment]
Worth merging

**Pull request merged**
