### PR TITLE
Update Zabbix to 4.0

### PR DESCRIPTION
**Pull request by tiemenruiten**
Some minor changes to ensure compatibility:
- replace deprecated method 'user.addmedia'
- replace escape characters in php-fpm.conf

Other changes:
- remove unused zabbix.repo file
- several small spelling/style corrections
- documentation

### CODE REVIEW

**Comment by hi-a** [comment]
Jenkins test this please

**Comment by hi-a** [comment]
Jenkings test this please

**Comment by dchirikov** [comment]
Jenkins test this please

**Comment by kostty** [comment]
Jenkins test this please

**Pull request merged**
